Describe nullability of columns in the create table schema endpoint
duneanalytics/dune-docs pull request #106
Opened 2024-04-05 14:10 UTC by dsalv

2024-04-05 14:10 UTC, dsalv commented
* **#106** <a href="https://app.graphite.dev/github/pr/duneanalytics/dune-api-docs/106?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @dsalv and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-05 15:27 UTC, waddahAldrobi commented on api-reference/tables/endpoint/create.mdx
> +  "schema": [{"name": "date", "type": "timestamp", "nullable": false}, {"name": "dgs10", "type": "double"}]
Can you align this schema, with rest of the schema definition's 👇

2024-04-08 07:43 UTC, hawkaa requested changes
We've forgotten to add this to the actual openapi schema. When that is done, we shouldn't need to write out a separate text paragraph describing the same thing.

2024-04-16 14:04 UTC, 0xBoxer commented
@duneanalytics/team-produce are you guys on this or are you watining on dev rel?

2024-04-16 14:13 UTC, dsalv commented
> @duneanalytics/team-produce are you guys on this or are you watining on dev rel?

Both works

2024-04-16 14:29 UTC, a-monteiro approved these changes

2024-04-16 15:43 UTC, helanto reviewed
A comment about the openAPI schema

2024-04-16 15:43 UTC, helanto commented on api-reference/tables/tables-openapi.json
> +            "example": "false"
Shouldn't this be:
```suggestion
            "example": false
```

2024-04-17 06:55 UTC, waddahAldrobi requested changes

2024-04-17 06:55 UTC, waddahAldrobi commented on api-reference/tables/endpoint/create.mdx
> +## Schema
Why this paragraph? 

I would just modify this
![image](https://github.com/duneanalytics/dune-docs/assets/28662355/70006e59-5f9e-408f-a7c0-11c35631e944)

2024-04-17 12:02 UTC, 0xBoxer commented on api-reference/tables/endpoint/create.mdx
> +## Schema
I'd think this helps users tbh, it's a nice and quick intro

2024-04-17 12:27 UTC, 0xBoxer commented
this lgtm from my perspective now, we can debate whether the text should be there or not, I think it helps to grog this on a quick glance.

2024-04-17 12:29 UTC, merged